In [2]:
print("hi")

hi


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2024-01-12 15:47:52.639165: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-12 15:47:52.811046: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-12 15:47:52.811070: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-12 15:47:52.837989: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-12 15:47:52.896791: I tensorflow/core/platform/cpu_feature_guar

TensorFlow version: 2.15.0


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

2024-01-12 15:49:30.616080: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-12 15:49:30.653187: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-12 15:49:30.653206: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-12 15:49:30.656890: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-01-12 15:49:30.656910: I external/local_xla/xla/stream_executor

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.367623  , -0.25703138, -0.31325832, -0.23957615,  0.4093979 ,
         0.33423895, -0.67611694, -0.09928939,  0.07183795, -0.31915438]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.14657316, 0.07848208, 0.07419103, 0.07986403, 0.15282594,
        0.14176072, 0.05161358, 0.09189184, 0.10904272, 0.07375489]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.9165444

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2024-01-12 04:11:06.812325: I external/local_xla/xla/service/service.cc:168] XLA service 0x7f221d4f29a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-01-12 04:11:06.812348: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Ti, Compute Capability 8.9
2024-01-12 04:11:06.819901: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-01-12 04:11:06.837492: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8906
I0000 00:00:1705032666.878450     230 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 [==============================] - 4s 2ms/step - loss: 0.3060 - accuracy: 0.9107
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1515 - accuracy: 0.9552
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1126 - accuracy: 0.9660
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0936 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0773 - accuracy: 0.9763


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0846 - accuracy: 0.9740 - 556ms/epoch - 2ms/step


[0.08463212847709656, 0.9739999771118164]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.08748232e-07, 8.56437005e-11, 1.67776932e-06, 1.65803154e-04,
        8.16776594e-12, 3.47838011e-07, 8.95870970e-14, 9.99815762e-01,
        1.92371701e-08, 1.63044733e-05],
       [1.78021651e-08, 1.13100663e-03, 9.98517931e-01, 3.50136863e-04,
        5.97203493e-14, 6.98960534e-08, 4.49382620e-09, 3.18984422e-11,
        7.60658736e-07, 2.25007689e-13],
       [2.27554528e-06, 9.99083996e-01, 1.11783294e-04, 3.15875295e-05,
        4.11077999e-05, 4.46307513e-06, 8.47138290e-06, 6.79520483e-04,
        3.43697211e-05, 2.47781509e-06],
       [9.99824822e-01, 1.60544964e-08, 5.31589649e-05, 4.98605868e-06,
        1.43915216e-07, 1.03197772e-06, 9.17191119e-06, 4.39219220e-05,
        3.26450533e-10, 6.27702757e-05],
       [2.00171184e-04, 5.38496581e-09, 6.70188774e-06, 3.62737092e-06,
        9.62719142e-01, 1.20087657e-06, 4.51907863e-06, 8.00594746e-04,
        9.31237264e-06, 3.62548120e-02]], dtype=float32)>